BlackJack application
kolintsio96/HilelC-Pro pull request #2
Opened 2023-11-18 12:38 UTC by kolintsio96

2023-11-20 13:52 UTC, Delvin09 requested changes
Нужно было создать отдельный репозиторий для игры, но уже ладно)
Следи за стилем и форматированием.

2023-11-20 13:52 UTC, Delvin09 commented on homework_3/BlackJack/PlayingCards.cs
> +        public Suits Suit { get; }
Многовато полей. достаточно же Suit и Denomination

2023-11-20 13:52 UTC, Delvin09 commented on homework_3/BlackJack/PlayingCards.cs
> +    readonly struct Card
выноси типы в отдельные файлы

2023-11-20 13:52 UTC, Delvin09 commented on homework_3/BlackJack/PlayingCards.cs
> +    internal class PlayingCards
Переименуй в колоду (Deck)

2023-11-20 13:52 UTC, Delvin09 commented on homework_3/BlackJack/PlayingCards.cs
> +        public Card[] GetCards()
а зачем?

2023-11-20 13:52 UTC, Delvin09 commented on homework_3/BlackJack/BlackJack.cs
> +        PlayingCards playingCards = new PlayingCards();
А не лучше создать класс Игрок, в который инкапсулировать его текущие карты и пр.?

2023-11-20 16:57 UTC, kolintsio96 commented on homework_3/BlackJack/PlayingCards.cs
> +        public Suits Suit { get; }
Згоден, зайві прибрав

2023-11-20 16:57 UTC, kolintsio96 commented on homework_3/BlackJack/PlayingCards.cs
> +    readonly struct Card
Добре

2023-11-20 16:58 UTC, kolintsio96 commented on homework_3/BlackJack/PlayingCards.cs
> +        public Card[] GetCards()
Прибрав цей метод

2023-11-20 17:20 UTC, kolintsio96 commented on homework_3/BlackJack/BlackJack.cs
> +        PlayingCards playingCards = new PlayingCards();
Додав клас Player

2023-11-21 10:32 UTC, Delvin09 approved these changes

2023-11-21 10:32 UTC, Delvin09 commented on homework_3/BlackJack/BlackJack.cs
> +                Play();
Рекурсия. Не думаю что это хорошее решение для данной ситуации.

2023-11-21 10:32 UTC, Delvin09 commented on homework_3/BlackJack/BlackJack.cs
> +        }
Делай отступ между методами

2023-11-21 10:32 UTC, Delvin09 commented on homework_3/BlackJack/BlackJack.cs
> +            Team team = ChoosePlayer();
Почему бы сразу не вернуть игроков в нужном порядке? Можно даже их расположить в массиве.

2023-11-21 10:32 UTC, Delvin09 commented on homework_3/BlackJack/Player.cs
> +            switch (denomination)
а еще можно enum сделать так, чтобы сразу возвращалось правильное кол-во очков

2023-11-21 11:16 UTC, kolintsio96 commented on homework_3/BlackJack/Player.cs
> +            switch (denomination)
Згоден, виправив

2023-11-21 11:17 UTC, kolintsio96 commented on homework_3/BlackJack/BlackJack.cs
> +        }
Буду звертати увагу на майбутнє, дякую

2023-11-21 11:22 UTC, kolintsio96 commented on homework_3/BlackJack/BlackJack.cs
> +                Play();
Мені здається, що тут неможливай варіант, коли рекурсія зациклиться, тому що ми нею керуємо через консоль.
І якщо ми хочемо грати повторно, тобто запускати гру ще раз, то це по суті і є рекурсія. Навіть якщо ми метод Play будемо визивати в методі Reset, то це всеодно буде рекурсія, які тут ще можуть бути варіанти?

2023-11-21 11:29 UTC, kolintsio96 commented on homework_3/BlackJack/BlackJack.cs
> +            Team team = ChoosePlayer();
Варіант з масивом цікавий, але в мене логіка для ходів комп'ютера і користувача різна, тому мені всеодно потрібно знати хто перший ходить (bool isUser), тому що далі я його ще використовую в різних місцях

2023-11-22 06:26 UTC, merged